DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    first VARCHAR(255) NOT NULL,
    amount_owed FLOAT,
    has_paid BOOLEAN DEFAULT false,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);